### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by MoShenGuo** [vulgur/python-tools#1]
你好  里面缺了好多文件 项目运行不起来

**Comment by MoShenGuo** [comment]
![image](https://user-images.githubusercontent.com/21171688/53137560-273edb80-35be-11e9-8e73-0359330dfe1b.png)

**Comment by MoShenGuo** [comment]
但是没有结果输出

**Comment by vulgur** [comment]
想不到这个东西居然还有人在用……好多年前写的了，我回忆一下啊。
project_path.txt 是指明项目所在目录，exclusions.txt 里都是不想被清理的文件名，一行一个。

**Comment by MoShenGuo** [comment]
好吧  网上搜到你的项目了 好多代码扫描都是几年前的 主要了解一下里面的原理

**Comment by vulgur** [comment]
> 好吧 网上搜到你的项目了 好多代码扫描都是几年前的 主要了解一下里面的原理

原理就是先扫代码里的资源饮用，然后扫资源文件夹里的文件，对比后删除
